<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>kuka_cartesian_setpoint_broadcaster</name>
  <version>0.9.2</version>
  <description>Broadcasts the RSI setpoint Cartesian pose (RSol) of KUKA robots as a geometry_msgs/Pose</description>

  <maintainer email="sachin.kumar@b-robotized.com">Sachin Kumar</maintainer>

  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>controller_interface</depend>
  <depend>pluginlib</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2</depend>
  <depend>std_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
