#ifndef KUKA_ROBOT_STATUS_BROADCASTER__VISIBILITY_CONTROL_H_
#define KUKA_ROBOT_STATUS_BROADCASTER__VISIBILITY_CONTROL_H_

// This logic was borrowed (then namespaced) from the examples on the gcc wiki:
//     https://gcc.gnu.org/wiki/Visibility

#if defined _WIN32 || defined __CYGWIN__
#ifdef __GNUC__
#define KUKA_ROBOT_STATUS_BROADCASTER_EXPORT __attribute__((dllexport))
#define KUKA_ROBOT_STATUS_BROADCASTER_IMPORT __attribute__((dllimport))
#else
#define KUKA_ROBOT_STATUS_BROADCASTER_EXPORT __declspec(dllexport)
#define KUKA_ROBOT_STATUS_BROADCASTER_IMPORT __declspec(dllimport)
#endif
#ifdef KUKA_ROBOT_STATUS_BROADCASTER_BUILDING_LIBRARY
#define KUKA_ROBOT_STATUS_BROADCASTER_PUBLIC KUKA_ROBOT_STATUS_BROADCASTER_EXPORT
#else
#define KUKA_ROBOT_STATUS_BROADCASTER_PUBLIC KUKA_ROBOT_STATUS_BROADCASTER_IMPORT
#endif
#define KUKA_ROBOT_STATUS_BROADCASTER_PUBLIC_TYPE KUKA_ROBOT_STATUS_BROADCASTER_PUBLIC
#define KUKA_ROBOT_STATUS_BROADCASTER_LOCAL
#else
#define KUKA_ROBOT_STATUS_BROADCASTER_EXPORT __attribute__((visibility("default")))
#define KUKA_ROBOT_STATUS_BROADCASTER_IMPORT
#if __GNUC__ >= 4
#define KUKA_ROBOT_STATUS_BROADCASTER_PUBLIC __attribute__((visibility("default")))
#define KUKA_ROBOT_STATUS_BROADCASTER_LOCAL __attribute__((visibility("hidden")))
#else
#define KUKA_ROBOT_STATUS_BROADCASTER_PUBLIC
#define KUKA_ROBOT_STATUS_BROADCASTER_LOCAL
#endif
#define KUKA_ROBOT_STATUS_BROADCASTER_PUBLIC_TYPE
#endif

#endif  // KUKA_ROBOT_STATUS_BROADCASTER__VISIBILITY_CONTROL_H_
